application:
    environment:
        php:
            version: 5.6.0
    type: none
filter:
    paths: [lib/*]
    excluded_paths: [vendor/*, tests/*]
before_commands:
    - 'composer install --dev --prefer-source'
checks:
    php:
        code_rating: true
        duplication: true
