language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install -n
  - mysql -u root -e 'create database ufuturehouse;'
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load --fixtures=src\Ufuturelabs\Ufuturehouse\Server\HousingBundle\DataFixtures\ORM\Catalogue

script: phpunit -c app
