security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        backend:
            pattern: ^/backend
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: backend_login
                check_path: backend_login_check
            logout: true
            anonymous: true

    access_control:
        - { path: ^/backend/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN