services:
    twig.extension.housing.get_type:
        class: Ufuturelabs\Ufuturehouse\Server\HousingBundle\Twig\HousingTypeExtension
        tags:
            - { name: twig.extension }

    ufuturehouse.util.catalogue:
        class: Ufuturelabs\Ufuturehouse\Server\HousingBundle\Util\CatalogueUtil