frontend_index:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_housing:
    resource: "@FrontendBundle/Resources/config/routing/housing.yml"
    prefix: /housing