backend_index:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }

backend_login:
    path:     /login
    defaults: { _controller: BackendBundle:Default:login }

backend_login_check:
    path: /login_check

backend_housing:
    resource: "@BackendBundle/Resources/config/routing/housing/housing.yml"
    prefix: /housing

backend_locations_state:
    resource: "@BackendBundle/Resources/config/routing/locations/state.yml"
    prefix: /locations/state

backend_locations_city:
    resource: "@BackendBundle/Resources/config/routing/locations/city.yml"
    prefix: /locations/city

backend_locations_zone:
    resource: "@BackendBundle/Resources/config/routing/locations/zone.yml"
    prefix: /locations/zone

backend_configuration:
    resource: "@BackendBundle/Resources/config/routing/configuration.yml"
    prefix: /conf

# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

backend_people:
    resource: "@BackendBundle/Resources/config/routing/people/people.yml"
    prefix: /people

