services:
    twig.extension.company:
        class: Ufuturelabs\Ufuturehouse\Server\BackendBundle\Twig\CompanyExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }
