services:
    twig.extension.company:
        class: Ufuturelabs\Ufuturehouse\Server\BackendBundle\Twig\CompanyExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    twig.extension.backend:
        class: Ufuturelabs\Ufuturehouse\Server\BackendBundle\Twig\BackendExtension
        tags:
            - { name: twig.extension }

    ufuturehouse.util:
        class: Ufuturelabs\Ufuturehouse\Server\BackendBundle\Util\Util
        arguments: [%kernel.root_dir%, @service_container]
