backend_locations_city_index:
    path:     /
    defaults: { _controller: BackendBundle:Locations:indexCity }

backend_locations_city_create:
    path:     /create
    defaults: { _controller: BackendBundle:Locations:createCity }

backend_locations_city_delete:
    path:     /delete/{id}
    defaults: { _controller: BackendBundle:Locations:deleteCity }