backend_locations_province_index:
    path:     /
    defaults: { _controller: BackendBundle:Locations:indexProvince }

backend_locations_province_create:
    path:     /create
    defaults: { _controller: BackendBundle:Locations:createProvince }

backend_locations_province_delete:
    path:     /delete/{id}
    defaults: { _controller: BackendBundle:Locations:deleteProvince }
