backend_locations_state_index:
    path:     /
    defaults: { _controller: BackendBundle:Locations:indexState }

backend_locations_state_create:
    path:     /create
    defaults: { _controller: BackendBundle:Locations:createState }

backend_locations_state_delete:
    path:     /delete/{id}
    defaults: { _controller: BackendBundle:Locations:deleteState }
